import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex text-center flex-col gap-4 mt-20">
        <h1 className="text-4xl text-blue-600">
          Hello, welcome to my very first firebase authentication project with
          NextJS
        </h1>
        <p className="text-xl text-gray-800">
          You can take a look at my{' '}
          <Link href="https://github.com/emrebican">
            <span className="font-bold cursor-pointer">github</span>
          </Link>{' '}
          projects
        </p>
        <p className="text-md text-gray-700">
          This project made powered by{' '}
          <span className="font-bold">
            <Link href="https://nextjs.org/docs/getting-started">NextJS</Link>
          </span>{' '}
          &{' '}
          <span className="font-bold">
            <Link href="https://firebase.google.com/docs?authuser=0&hl=en">
              Firebase
            </Link>
          </span>{' '}
          &{' '}
          <span className="font-bold">
            <Link href="https://tailwindcss.com/docs/installation">
              TailwindCss
            </Link>
          </span>
        </p>
      </main>
    </div>
  );
}
